//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string WAIST_RIGHT = "waist_right";
        
        public const string RIGHTHANDLOWWEIGHTS = "righthandlowweights";
        
        public const string FOREARM_LEFT = "forearm_left";
        
        public const string HEARTBEAT_FAST = "heartbeat_fast";
        
        public const string CHEST_LEFT = "chest_left";
        
        public const string EXPLOSION = "explosion";
        
        public const string FRONTBODY_CENTER = "frontbody_center";
        
        public const string SHOULDER_RIGHT = "shoulder_right";
        
        public const string SHOULDER_LEFT = "shoulder_left";
        
        public const string HEAD_ALL = "head_all";
        
        public const string RIGHTHANDMEDIUMWEIGHTS = "righthandmediumweights";
        
        public const string GAME_START = "game_start";
        
        public const string ELECTRICSHOCK = "electricshock";
        
        public const string HEARTBEAT = "heartbeat";
        
        public const string DRINKPOTION = "drinkpotion";
        
        public const string LEFTHANDMEDIUMWEIGHTS = "lefthandmediumweights";
        
        public const string HEAD_RIGHT = "head_right";
        
        public const string FOREARM_RIGHT = "forearm_right";
        
        public const string HEAD_LEFT = "head_left";
        
        public const string CHEST_RIGHT = "chest_right";
        
        public const string RIGHTHANDHEAVYWEIGHTS = "righthandheavyweights";
        
        public const string HEALING = "healing";
        
        public const string FLAMEBURNING = "flameburning";
        
        public const string LEFTHANDLOWWEIGHTS = "lefthandlowweights";
        
        public const string EATFOOD = "eatfood";
        
        public const string LEFTHANDHEAVYWEIGHTS = "lefthandheavyweights";
        
        public const string WAIST_LEFT = "waist_left";
    }
}
